{% set version = "1.2" %}

package:
  name: artview
  version: {{ version }}

source:
  fn: artview-{{ version }}.tar.gz
  url: https://github.com/nguy/artview/archive/v{{ version }}.tar.gz
  sha256: db88e269a319b42781fab6016b029c3e07446cc7899135d78b46a62e4ae512ca

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - arm_pyart >=1.5
    - matplotlib >=1.1
    - pyqt >=4.6
  run:
    - python
    - arm_pyart >=1.5
    - matplotlib >=1.1
    - pyqt >=4.6

test:
  imports:
    - artview

about:
  home: https://github.com/nguy/artview
  license: BSD 3-Clause
  summary: ARM Radar Toolkit Viewer

extra:
  recipe-maintainers:
    - jjhelmus
